### PR TITLE
Mt script fixes

### PR DESCRIPTION
**Pull request by Xariyl**
New file for Nether items.

### CODE REVIEW

**Comment by Xariyl** [comment]
I made them kind of cheap on purpose, but I can adjust them. I'm open to suggestions, I'll look at the blocks of coal but not sure how I'll handle the sulfur.

Looking at the [comparison sheet](https://docs.google.com/spreadsheets/d/1lAQeIayx7UOBRskelBjXnxslD4qPwSo3sHIN-adeOBM/edit#gid=0) you showed me: Cobalt is comparable to Alumite and Ferrous in durability; Ardite is weaker than Bronze but is a good handle modifier; across the board they are comparable to Ferrous which isn't all that hard to get. Shiny is faster mining and higher attack than Manyullym, Many only has a higher durability and handle modifier, and of course is the only material that can mine itself. 

So like all things, their use is situational and not the best for every occasion. I figured the extra steps of using the sulfer and charcoal dusts, and then resmelting into ingots would be cost enough.

**Comment by AlexTheGre4t** [comment]
Yeah, very good thinking with that. I very much like your ideas for them. Ill pull your stuff tomorrow when I get home :)

**Comment by Xariyl** [comment]
https://youtu.be/xdGSqs4XmyA

Liquid Pyrotheum to Blaze Rods!

**Comment by Xariyl** [comment]
- Increased the amount of Nickel required to a full ingot, instead of half.
- Allowed TF and RC sulfur / charcoal dusts until the Unifications are updated. Will load to server, but recommend holding off on committing the PR until we finalize it.

**Comment by AlexTheGre4t** [comment]
pulling, will update pack later

**Pull request merged**
